### ISSUE TITLE
The Map block doesn't allow custom identifiers

### ISSUE THREAD

**Issue by J-Verz** [NiekAukes/eca2#13]
Something like this:
```html
<div id="my-map"></div>
<script>
let my_map = leaflet("my-map");
connect_block(my_map, "my_block_key");
</script>
```
doesn't work, the identifier has to be `map` in order for it to work.

It looks like the identifier passed into `leaflet()` is never used.

**Comment by NiekAukes** [comment]
thanks for notifying, it will be released in the next update
